### ISSUE TITLE
Implementierung eines CO2-Trackers für den täglichen Verbrauch

### ISSUE THREAD

**Issue by Roba42** [Roba42/MoCo_SS23_FootPrintHero#5]
**Beschreibung**: Wir möchten eine Funktion hinzufügen, mit der Nutzer ihren täglichen CO2-Verbrauch verfolgen können.

**Anforderungen**:

- [ ] Erstellung einer Datenbank-Tabelle für den CO2-Verbrauch

- [ ] Implementierung einer Schnittstelle zum Hinzufügen von CO2-Verbrauchsdaten

- [ ] Implementierung einer Schnittstelle zur Anzeige der gesammelten CO2-Daten

**Comment by PhilippZimmer** [comment]
Wären hier nicht hardcoded Werte genug?

**Comment by PhilippZimmer** [comment]
Der Fehler kommt auch in der Neuen Version wenn man RUN benutz:

FATAL EXCEPTION: main
Process: com.example.prototype_footprinthero, PID: 6559
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.prototype_footprinthero/com.example.prototype_footprinthero.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:781)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:209)
	at androidx.activity.compose.ComponentActivityKt.setContent(ComponentActivity.kt:67)
	at androidx.activity.compose.ComponentActivityKt.setContent$default(ComponentActivity.kt:48)
	at com.example.prototype_footprinthero.MainActivity.onCreate(MainActivity.kt:58)
	at android.app.Activity.performCreate(Activity.java:8305)
	at android.app.Activity.performCreate(Activity.java:8284)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7872) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
